### ISSUE TITLE
[api] Creación EndPoint obtención de observaciones

### ISSUE THREAD

**Issue by PeteRey** [PeteRey/diy-satellites#3]
`api/v1/observations/?init_time=2020-06-23T00:00:00&end_time=2020-06-24T00:00:00`

Como parámetro opcional `bbox`

**Comment by michogar** [comment]
Acuerdate que usamos 

https://www.django-rest-framework.org/

y su parte GIS

https://github.com/openwisp/django-rest-framework-gis
